config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :admin_users
    namespace :admin do
     get 'admin_users/index'
  end

  devise_scope :admin_user do
   get "/admin" => "devise/sessions#new"
  end
  namespace :admin do
    resources :admin_users 
    resources :home   
    resources :employees do
      collection do
        get "set_datatable_employees"
      end
    end 
    resources :products do
      collection do
        get "set_datatable_products"
      end
    end  
    resources :optimize
    resources :type_resource do
      collection do
        get "set_datatable_type_resources"
      end
    end 
    resources :production do
      collection do
        post "employee_hour"
        post "create_work"
        post "create_resource"
        get "set_datatable_resource"
        delete "destroy_resource"
      end
      member do
        get "resources"
        get "show_details"
      end
    end
    root 'home#index'

  end
  root 'landpage#index'
  
end

app/models/employee.rb
class Employee < ApplicationRecord
	has_many :works
end

app/controllers/admin/employees_controller.rb
class Admin::EmployeesController < AdminController
	before_action :authenticate_admin_user!
	before_action :set_employee, only:[:show, :edit, :update, :destroy]
	
	def index
	end

	def show
	end

	def new
		@employee = Employee.new
	end
	
	def create
		
		respond_to do |format|
            @employee = Employee.new(employee_params)
            if @employee.save
                format.html {redirect_to :back,:notice=>"Funcionário criado com sucesso."}
            else
                format.html {redirect_to :back,:alert=>"Falha ao criar funcionário."}
            end
        end
	end

	def update
		respond_to do |format|
            if @employee.update(employee_params)
                format.html {redirect_to :back,:notice=>"Funcionário atualizada com sucesso."}
            else
                format.html {redirect_to :back,:alert=>"Falha ao atualizar funcionário."}
            end
        end
	end

	def destroy
        
        respond_to do |format|
            if @employee.destroy
                format.html {redirect_to :back,:notice=>"Funcionário deletado com sucesso."}
            else
                format.html {redirect_to :back,:alert=>"Falha ao deletar funcionário."}
            end
        end
    end

	def set_datatable_employees

        respond_to do |format|
            format.html
            format.json { render json: EmployeeDatatable.new(view_context) }
        end 
    end

    private

    def set_employee
    	@employee = Employee.find(params[:id])
    end	

    def employee_params
    	params.require(:employee).permit(:name, :email, :work_hours)
    end
end

app/views/admin/employees/edit.html.erb
<!--END MODAL-->
<%= simple_form_for @employee, :url => admin_employee_path(@employee.id), :method => :patch,html: { id:'form-employee', class: 'form-horizontal' }, wrapper: :horizontal_form,
wrapper_mappings: {
  check_boxes: :horizontal_radio_and_checkboxes,
  radio_buttons: :horizontal_radio_and_checkboxes,
  file: :horizontal_file_input,
  boolean: :horizontal_boolean } do |f| %>
  <%= f.error_notification %>
  <div class="alert alert-danger" id="date_invalid" style="padding-bottom:10px" hidden>Data de nascimento inválida!</div>
  <% if flash[:notice] %>
     <div class="alert alert-success" id="js_success" style="padding-bottom:10px"><%= flash[:notice] %></div>
  <% end %>
  <% if flash[:alert] %>
     <div class="alert alert-danger" style="padding-bottom:10px"><%= flash[:error] %></div>
  <% end %>
  <div class="panel">
    <div class="panel-heading">
      <span class="panel-title">Editar funcionário</span>
    </div>
    <div class="panel-body">

      <div class="row">
        <div class="col-md-9">
          <%= f.input :name, label:'Nome'%>
        </div>
      </div>

      <div class="row">
        <div class="col-md-9">
          <%= f.input :email, label:'E-mail'%>
        </div>
      </div>

      <div class="row">
        <div class="col-md-9">
          <%= f.input :work_hours, label:'E-mail'%>
        </div>
      </div>

      <div class="panel-footer text-right">
        <input type="submit" name="commit" value="Salvar" id="save-user-btn" class="btn btn-primary" data-disable-with="Salvar">      
      </div>
    </div>

<% end %>

app/views/admin/employees/index.html.erb
<% content_for :topbar_left do %>
  <ol class="breadcrumb">
    <% content_for :topbar_right do %>
        <%= link_to( new_admin_employee_path, id: 'muscle-add-btn', class: 'btn btn-default btn-sm light fw600 ml10', style: " background-color: #18BC9C; color: #fff") do %>
        <i class="fa fa-plus pr5"></i> Novo funcionário
      <% end %>
    <% end %>
    <li class="crumb-active">
      <span class="glyphicon glyphicon-user mr5"></span>
      <a href="">Funcionários</a>
      
    </li>
  </ol>
<% end %>

<div class="panel">
  <div class="panel-body">
   <table class="table table-hover" id="emp-table" data-source="<%=set_datatable_employees_admin_employees_path(format: :json) %>"
        cellspacing="0" width="100%">
        <thead>        
          <tr>
            <th>Nome</th>
            <th>E-mail</th>
            <th>Horas semanais</th>
            <th>Ações</th>
            </tr>
          </thead>
          <tbody>
          </tbody>
        </table>
  </div>
</div>

app/views/admin/employees/new.html.erb
<!--END MODAL-->
<%= simple_form_for @employee, :url => "/admin/employees", :method => :post,html: { id:'form-employee', class: 'form-horizontal',:method => :post }, wrapper: :horizontal_form,
wrapper_mappings: {
  check_boxes: :horizontal_radio_and_checkboxes,
  radio_buttons: :horizontal_radio_and_checkboxes,
  file: :horizontal_file_input,
  boolean: :horizontal_boolean } do |f| %>
  <%= f.error_notification %>
  <div class="alert alert-danger" id="date_invalid" style="padding-bottom:10px" hidden>Data de nascimento inválida!</div>
  <% if flash[:notice] %>
     <div class="alert alert-success" id="js_success" style="padding-bottom:10px"><%= flash[:notice] %></div>
  <% end %>
  <% if flash[:alert] %>
     <div class="alert alert-danger" style="padding-bottom:10px"><%= flash[:error] %></div>
  <% end %>
  <div class="panel">
    <div class="panel-heading">
      <span class="panel-title">Novo funcionário</span>
    </div>
    <div class="panel-body">

      <div class="row">
        <div class="col-md-9">
          <%= f.input :name, label:'Nome'%>
        </div>
      </div>

      <div class="row">
        <div class="col-md-9">
          <%= f.input :email, label:'E-mail'%>
        </div>
      </div>

      <div class="row">
        <div class="col-md-9">
          <%= f.input :work_hours, as: :string, label:'Horas semanais'%>
        </div>
      </div>

      <div class="panel-footer text-right">
        <input type="submit" name="commit" value="Salvar" id="save-user-btn" class="btn btn-primary" data-disable-with="Salvar">      
      </div>
    </div>

<% end %>

app/views/admin/employees/show.html.erb
<div class="panel">
  <div class="panel-heading">
    <span class="panel-title">Detalhes do funcionário</span>
  </div>
  <div class='admin-form theme-primary'>
    <div class="panel-body">
      <div class="col-md-4">
       
      <div class="col-md-5">
        <div class="col-md-12 mb10">
          <b>Nome</b><br>
            <%= @employee.name %>
          </div>
        <div class="col-md-12 mb10">
          <b>E-mail</b><br>
            <%= @employee.email %>
          </div>      

      </div>
      
    </div>
  </div>
</div>