config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :admin_users
    namespace :admin do
     get 'admin_users/index'
  end

  devise_scope :admin_user do
   get "/admin" => "devise/sessions#new"
  end
  namespace :admin do
    resources :admin_users 
    resources :home   
    resources :employees do
      collection do
        get "set_datatable_employees"
      end
    end 
    resources :products do
      collection do
        get "set_datatable_products"
      end
    end  
    resources :optimize
    resources :type_resource do
      collection do
        get "set_datatable_type_resources"
      end
    end 
    resources :production do
      collection do
        post "employee_hour"
        post "create_work"
        post "create_resource"
        get "set_datatable_resource"
        delete "destroy_resource"
      end
      member do
        get "resources"
        get "show_details"
      end
    end
    root 'home#index'

  end
  root 'landpage#index'
  
end

app/controllers/admin/production_controller.rb
class Admin::ProductionController < AdminController
	before_action :authenticate_admin_user!
	before_action :set_product, only:[:show_details]
	before_action :set_employees, only:[:index]
	before_action :set_resources, only:[:index]
	before_action :set_resource, only:[:destroy_resource]
	def index
		@work = Product.joins(:works).group(:product_id)
		@works = Work.new
		@resource = Resource.new
	end

	def employee_hour
		@work = Work.new
	end

	def resources
		@resource = Resource.new
	end

	def show_details
		@employees = Work.where(product_id: @product.id)

	end

	def create_resource
	  
		respond_to do |format|
			@resource = Resource.new
			@resource.name = params[:name]
			@resource.quantity = params[:resource][:quantity]
			@resource.product_id = params[:products]
			if @resource.save
		    	format.html {redirect_to :back,:notice=>"Restrição do produto #{Product.find(@resource.product_id).name} criada com sucesso."}
			else
		    	format.html {redirect_to :back,:alert=>"Falha ao criar produção do produto #{Product.find(@resource.product_id).name}."}
			end
		end
		
	end

	def create_work
		@work = Work.new
		@work.hour_per_unit = params[:work][:hour_per_unit].to_i
		@work.employee_id = params[:work][:employee_id]
		@work.product_id = params[:work][:product_id]
		@work.save 		
	end

	def destroy_resource
		respond_to do |format|
            if @resource.destroy
                format.html {redirect_to :back,:notice=>"Recurso deletado com sucesso."}
            else
                format.html {redirect_to :back,:alert=>"Falha ao deletar recurso."}
            end
        end
	end

	def new
		@work = Work.new
		@employees = Employee.all.pluck(:name,:id)
		@products = Product.all.pluck(:name,:id)
	end

	def set_datatable_resource

        respond_to do |format|
            format.html
            format.json { render json: ResourceDatatable.new(view_context, {product_id: params[:product_id]}) }
        end 
    end

   

private

	def product_params
    	params.require(:product).permit(:name, :description, :net_profit)
    end

    def resource_params
    	params.require(:resource).permit(:name, :operation, :quantity, :product_id)    	
	end

	def set_employees
		@employees = Employee.all.pluck(:name,:id)
	end

	def set_resource
		@resource = Resource.find(params[:id])
	end
	def set_product
		@product = Product.find(params[:id])
	end
	
	def set_resources
		@resources = TypeResource.all.pluck(:name)
	end


end

app/views/admin/production/employee_hour.html.erb
 <div class="wrapper">
  <div class="panel">
    <div class="panel-heading">
      <span class="panel-title">Produção do produto <%=Product.find(params[:products]).name%></span>
    </div>
  </div>

  <%params[:employees].each_with_index do |employee_id,index| %>

    <!--END MODAL-->
    <%= simple_form_for @work, :url => "/admin/production/create_work", data:{id: index},:method => :post,html: { id:index, class: 'form-horizontal',:method => :post }, wrapper: :horizontal_form,
    wrapper_mappings: {
      check_boxes: :horizontal_radio_and_checkboxes,
      radio_buttons: :horizontal_radio_and_checkboxes,
      file: :horizontal_file_input,
      boolean: :horizontal_boolean } do |f| %>
      <%= f.error_notification %>
      <% if flash[:notice] %>
         <div class="alert alert-success" id="js_success" style="padding-bottom:10px"><%= flash[:notice] %></div>
      <% end %>
      <div class="alert alert-danger" id="js_error" style="padding-bottom:10px" hidden></div>
      <% if flash[:alert] %>
         <div class="alert alert-danger" style="padding-bottom:10px"><%= flash[:alert] %></div>
      <% end %>
          
      <%@emp = Employee.find(employee_id)%>
      <div class="panel">
        <div class="panel-body">
          <div class="alert alert-success hidden" id="js_success-<%=index%>" style="padding-bottom:10px">Salvo com sucesso!</div>
          <div class="alert alert-danger hidden" id="js_error-<%=index%>" style="padding-bottom:10px">Verifique os campos em vermelho.</div>
          <div class="row">
            <div class="col-md-2">
              <label><%=@emp.name%></label>
            </div>
            <div class="col-md-5">
               <%= f.input :hour_per_unit, as: :string, label:"Horas gastas por unidade", input_html:{class:"hour_per_unit", value:"0"}%>
               <div class="hidden">
               <%= f.input :label_id, as: :string, label:" ", input_html:{value: index }%>
              </div>
            </div>
            
          </div>

          <div class="hidden">
               <%= f.input :product_id, as: :string, label:" ", input_html:{value: params[:products] }%>
               <%= f.input :employee_id, as: :string, label:" ", input_html:{value: params[:employees][index]}%>
          </div>
        </div>
        <div class="panel-footer text-right">
          <input type="button" name="commit" value="Cancelar" id="save-user-btn-<%=index%>" class="btn btn-danger" data-disable-with="Salvar">  
          <input type="button" name="commit" value="Salvar" id="save-user-btn-<%=index%>" class="btn btn-primary btn-submit" data-disable-with="Salvar">  
        </div>
      </div>
    <%end%>
    </div>
  <% end %>


</div>

app/views/admin/production/index.html.erb
<% content_for :topbar_left do %>
  <ol class="breadcrumb">
    <% content_for :topbar_right do %>
        <%= link_to( new_admin_production_path, id: 'muscle-add-btn', class: 'btn btn-default btn-sm light fw600 ml10', style: " background-color: #9ACC77; color: #fff") do %>
        <i class="fa fa-plus pr5"></i> Nova produção
      <% end %>
    <% end %>
    <li class="crumb-active">
      <span class="glyphicon glyphicon-user mr5"></span>
      <a href="">Produções</a>


      
    </li>
  </ol>
<% end %>
<% if flash[:notice] %>
      <div class="alert alert-success" id="js_success" style="padding-bottom:10px"><%= flash[:notice] %></div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-danger" style="padding-bottom:10px"><%= flash[:error] %></div>
    <% end %>

<%@work.each_with_index do |work,index| %>
    
  <div class="col-md-4">
    
    <div class="w3-card-4" style="background-color: #fff;">
      <header class="w3-container" style="background-color: #000;">
        <h1 style="font-size:18px;color:#fff;"><%=work.name%></h1>
      </header>

      <div class="w3-container" style="margin-top: 10px;background-color: #fff;">
        <p><%=work.description%></p>
        
        <p><label>Lucro:</label> R$<%=work.net_profit%></p>
      </div>
      
      <% @link = "/admin/production/" + work.id.to_s + "/show_details"%>
      <div class="row box-func hidden " style="padding: 8px;">
        <div class="col-lg-12" >Funcionários alocados para produção
          <%= simple_form_for @works, :url => "/admin/production/employee_hour", :method => :post,html: { id:'form-employee', class: 'form-horizontal' }, wrapper: :horizontal_form, wrapper_mappings: {
              check_boxes: :horizontal_radio_and_checkboxes,
              radio_buttons: :horizontal_radio_and_checkboxes,
              file: :horizontal_file_input,
              boolean: :horizontal_boolean } do |f| %>
            <input type="text" name="products" class="product_id hidden" value="<%=work.id%>">

            <%= select_tag "employees", options_for_select(@employees), id:"employees", style:"width:100% !important", class: "form-control multiple-select",multiple: true, :require=>true%>    
            <input type="submit" name="commit" value="Salvar" style="margin-top: 10px;width: 100%;background-color: #9ACC77; color:#fff;" class="btn btn-primary" data-disable-with="Salvar">
          <%end%>
        </div>
      </div>
      
      <button class="w3-button w3-block opt-func" style="background-color: #334F53;color:#fff;" href='<%=@link%>' >Adicionar funcionários</button>
      <hr style="margin:0 !important;">

      <div class="row box-rec hidden" style="padding: 8px;">
        <div class="col-lg-12" >Recursos alocados para produção
          <%= simple_form_for @resource, :url => create_resource_admin_production_index_path , :method => :post,html: { id:'form-employee', class: 'form-horizontal',:method => :post }, wrapper: :horizontal_form, wrapper_mappings: {
          check_boxes: :horizontal_radio_and_checkboxes,
          radio_buttons: :horizontal_radio_and_checkboxes,
          file: :horizontal_file_input,
          boolean: :horizontal_boolean } do |f| %>
            <div class="col-md-12">
              <%= select_tag "name", options_for_select(@resources), style:"width:100% !important", class: "form-control",multiple: false, :require=>true%>
            </div>
            <input type="text" name="products" class="product_id hidden" value="<%=work.id%>">
            <div class="col-md-12" style="font-size: 12px; margin-top: 10px;">
              <%= f.input :quantity, as: :string, label:'Quantidade', input_html:{value:"0"}%>
              <div class="hidden">
                <%= f.input :product_id, as: :string, label:'Product id', input_html:{value:work.id, class: "hidden"}%>
              </div>  
            </div>
            <input type="submit" name="commit" value="Salvar" style="margin-top: 10px;width: 100%;background-color: #9ACC77; color:#fff;" class="btn btn-primary" data-disable-with="Salvar">
          <%end%>
        </div>
      </div>
      
      <button class="w3-button w3-block opt-rec " style="background-color: #334F53;color:#fff;" >Adicionar restrições</button>
      <hr style="margin:0 !important;">
      <a class="w3-button w3-block " style="background-color: #334F53;color:#fff;" href='<%=@link%>' >Ver mais</a>
    </div>
  </div>  

  
<%end%>

app/views/admin/production/new.html.erb
<!--END MODAL-->
<%= simple_form_for @work, :url => "/admin/production/employee_hour", :method => :post,html: { id:'form-employee', class: 'form-horizontal' }, wrapper: :horizontal_form,
wrapper_mappings: {
  check_boxes: :horizontal_radio_and_checkboxes,
  radio_buttons: :horizontal_radio_and_checkboxes,
  file: :horizontal_file_input,
  boolean: :horizontal_boolean } do |f| %>
  <%= f.error_notification %>
  <% if flash[:notice] %>
     <div class="alert alert-success" id="js_success" style="padding-bottom:10px"><%= flash[:notice] %></div>
  <% end %>
  <div class="alert alert-danger" id="js_error" style="padding-bottom:10px" hidden></div>
  <% if flash[:alert] %>
     <div class="alert alert-danger" style="padding-bottom:10px"><%= flash[:alert] %></div>
  <% end %>
  <div class="panel">
    <div class="panel-heading">
      <span class="panel-title">Nova produção</span>
    </div>
    <div class="panel-body">

      <div class="row">
        <div class="col-md-9">Produtos
          <%= select_tag "products", options_for_select(@products), id:"products", class: "form-control multiple-select",multiple: false, :require=>true%>
        </div>
      </div>

      <div class="row">
        <div class="col-md-9">Funcionários alocados para produção
          <%= select_tag "employees", options_for_select(@employees), id:"employees", class: "form-control multiple-select",multiple: true, :require=>true%>
        </div>
      </div>

      
    </div>
    <div class="panel-footer text-right">
        <input type="submit" name="commit"  value="Salvar" id="save-user-btn" class="btn btn-primary" data-disable-with="Salvar">      </div>
    </div>

<% end %>

app/views/admin/production/resources.html.erb
<!--END MODAL-->
<%= simple_form_for @resource, :url => create_resource_admin_production_index_path , :method => :post,html: { id:'form-employee', class: 'form-horizontal',:method => :post }, wrapper: :horizontal_form,
wrapper_mappings: {
  check_boxes: :horizontal_radio_and_checkboxes,
  radio_buttons: :horizontal_radio_and_checkboxes,
  file: :horizontal_file_input,
  boolean: :horizontal_boolean } do |f| %>
  <%= f.error_notification %>
  <div class="alert alert-danger" id="date_invalid" style="padding-bottom:10px" hidden>Data de nascimento inválida!</div>
  <% if flash[:notice] %>
     <div class="alert alert-success" id="js_success" style="padding-bottom:10px"><%= flash[:notice] %></div>
  <% end %>
  <% if flash[:alert] %>
     <div class="alert alert-danger" style="padding-bottom:10px"><%= flash[:error] %></div>
  <% end %>
  <div class="panel">
    <div class="panel-heading">
      <span class="panel-title">Nova restrição</span>
    </div>
    <div class="panel-body">

      <div class="row">
        <div class="col-md-9">
          <%= f.input :name, label:'Nome'%>
        </div>
      </div>

      <div class="row">
        <div class="col-md-9">
          <%= f.input :operation, label:'Operação', :collection=>["<=", ">=", "<", ">", "="], include_blank: false%>
        </div>
      </div>

      <div class="row">
        <div class="col-md-9">
          <%= f.input :quantity, as: :string, label:'Quantidade'%>
        </div>
      </div>

       <div class="row" hidden>
        <div class="col-md-9">
          <%= f.input :product_id, as: :string, label:'ID', input_html:{value:params[:id]}%>
        </div>
      </div>

      <div class="panel-footer text-right">
        <%=link_to("Cancelar",  admin_production_index_path , {class: 'btn btn-danger'} )%>
        <input type="submit" name="commit" value="Salvar" id="save-user-btn" class="btn btn-primary" data-disable-with="Salvar">      
      </div>
    </div>

<% end %>

app/views/admin/production/show_details.html.erb
<% content_for :topbar_left, style:"background-color: #18BC9C" do %>
  <ol class="breadcrumb">
    <li class="crumb-active">
      <span class="glyphicon glyphicon-user mr5"></span>
      <a href="">Detalhes do produto</a>
      
    </li>
  </ol>
<% end %>

    <div class="card hovercard"  style="background-color: #1F0A1D">
        <div class="card-background">
            <img class="card-bkimg" alt="" >
            <!-- http://lorempixel.com/850/280/people/9/ -->
        </div>
        <div class="useravatar">
            <img alt="" src="/assets/company.png">
        </div>
        <div class="card-info"> <span class="card-title" style="background-color: #1F0A1D;color:#E5EAD4"><%=@product.name%></span>

        </div>
    </div>
    <div class="btn-pref btn-group btn-group-justified btn-group-lg" role="group" aria-label="...">
        <div class="btn-group" role="group">
            <button type="button" id="stars" class="btn btn-show-green" href="#tab1" data-toggle="tab"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                <div class="hidden-xs">Funcionários</div>
            </button>
        </div>
        <div class="btn-group" role="group">
            <button type="button" id="favorites" class="btn btn-default" href="#tab2" data-toggle="tab"><span class="fa fa-gear" aria-hidden="true"></span>
                <div class="hidden-xs">Restrições</div>
            </button>
        </div>
        
    </div>

        
    <div class="panel">
      <div class="row">
        <div class="container">
          <div class="tab-content">
            <div class="tab-pane fade in active"  id="tab1">
              <%@employees.each do |employee|%>
                  <%@emp = Employee.find(employee.employee_id)%>
                  <div class="col-md-4" style="padding:30px;">
                      <div class="w3-card-4 " style="width:92%;max-width:230px;">
                          <img src="/assets/img_avatar.png" alt="Avatar" style="width:100%;opacity:0.85">
                          <div class="w3-container">
                          <h4><b><%=@emp.name%></b></h4>    
                          <p><label>Horas semanais:</label> <%=@emp.work_hours%></p> 
                          <p><label>Horas nesse produto:</label> <%=employee.hour_per_unit%></p>   
                          </div>
                       </div>
                   </div>
                 
               <%end%>
            </div>
            <div class="tab-pane fade in" id="tab2">
                <div class="panel">
                  <div class="panel-body">
                  <
                   <table class="table table-hover" id="rest-table" data-source="<%= set_datatable_resource_admin_production_index_path(product_id: params[:id],format: :json) %>"
                        cellspacing="0" width="100%">
                        <thead>        
                          <tr>
                            <th>Nome</th>
                            <th>Quantidade</th>
                            <th>Disponibilidade</th>
                            </tr>
                          </thead>
                          <tbody>
                          </tbody>
                        </table>
                  </div>
                </div>

            </div>
       </div>
    </div>
    
    
  
            
    