config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :admin_users
    namespace :admin do
     get 'admin_users/index'
  end

  devise_scope :admin_user do
   get "/admin" => "devise/sessions#new"
  end
  namespace :admin do
    resources :admin_users 
    resources :home   
    resources :employees do
      collection do
        get "set_datatable_employees"
      end
    end 
    resources :products do
      collection do
        get "set_datatable_products"
      end
    end  
    resources :optimize
    resources :type_resource do
      collection do
        get "set_datatable_type_resources"
      end
    end 
    resources :production do
      collection do
        post "employee_hour"
        post "create_work"
        post "create_resource"
        get "set_datatable_resource"
        delete "destroy_resource"
      end
      member do
        get "resources"
        get "show_details"
      end
    end
    root 'home#index'

  end
  root 'landpage#index'
  
end

app/views/admin/shared/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/admin/shared/_navbar.html.erb
<header class="navbar navbar-fixed-top" style="background-color: #334F53 !important">
  <div class="navbar-branding">
    <a class="navbar-brand" data-no-turbolink="true" href="<%= admin_root_path %>" style="font-size:30px;color:#fff;">OTIMEASY</a>
  </div>

  <ul class="nav navbar-nav navbar-right" >

    <li class="dropdown menu-merge nav-menu">
      <a href="#" class="dropdown-toggle fw600 name" data-toggle="dropdown" aria-expanded="true">
        <i class="glyphicons glyphicons-user"></i>
        <span class="pl5"><%=current_admin_user.email%> </span>
        <span class="caret caret-tp"></span>
      </a>

      <ul class="dropdown-menu list-group dropdown-persist w250" role="menu">
        <li class="list-group-item text-center">
            <%= link_to(edit_admin_admin_user_path(current_admin_user.id)) do %>
            <span class="fa fa-gear"></span> Configurações
            <%end%>
        </li>
        <li class="dropdown-footer">
          <%= button_to(destroy_admin_user_session_path, method: :delete, class: 'btn btn-link btn-block logout-btn') do %>
            <span class="fa fa-power-off pr5"></span> Sair
          <% end %>
        </li>
      </ul>
    </li>

  </ul>
</header>

app/views/admin/shared/_sidebar.html.erb
<aside id="sidebar_left" class="affix sidebar-light nano" style="background-color: #1F0A1D;">

  <!-- Start: Sidebar Left Content -->
  <div class="sidebar-left-content nano-content">

    <!-- Start: Sidebar Left Menu -->
    <ul class="nav sidebar-menu">
      

      <%if current_admin_user%>
      <li class="<% if controller_name == 'home' %>box-sidebar<% end %>">
        <%= link_to( admin_home_index_path ) do %>
          <span class="glyphicon glyphicon-home"></span>
          <span class="sidebar-title">Home</span>

          <span class="sidebar-title-tray" id="">
           
          </span>
        <% end %>
      </li>
      <hr class="label-line"></hr>
      <li class="<% if controller_name == 'employees' %>box-sidebar<% end %>">
        <%= link_to(admin_employees_path) do %>
          <span class="<% if controller_name == 'employees' %>label-sidebar<% end %>" style="font-size: 16px;font-weight: bold;">1º</span>
          <span class="sidebar-title">Funcionários</span>

          <span class="sidebar-title-tray" id="">
           
          </span>
        <% end %>
      </li> 
      
      <li class="<% if controller_name == 'products' %>box-sidebar<% end %>">
        <%= link_to(admin_products_path) do %>
          <span class="<% if controller_name == 'products' %>label-sidebar<% end %>" style="font-size: 16px;font-weight: bold;">2º</span>
          <span class="sidebar-title">Produtos</span>

          <span class="sidebar-title-tray" id="">
           
          </span>
        <% end %>
      </li>    

      <li class="<% if controller_name == 'type_resource' %>box-sidebar<% end %>">
        <%= link_to( admin_type_resource_index_path ) do %>
          <span class="<% if controller_name == 'type_resource' %>label-sidebar<% end %>" style="font-size: 16px;font-weight: bold;">3º</span>
          <span class="sidebar-title">Recursos</span>

          <span class="sidebar-title-tray" id="">
           
          </span>
        <% end %>
      </li>  
      
      <li class="<% if controller_name == 'production' %>box-sidebar<% end %>">
        <%= link_to(admin_production_index_path) do %>
          <span class="<% if controller_name == 'production' %>label-sidebar<% end %>" style="font-size: 16px;font-weight: bold;">4º</span>
          <span class="sidebar-title">Produção</span>

          <span class="sidebar-title-tray" id="">
           
          </span>
        <% end %>
      </li>    
      
      <li class="<% if controller_name == 'optimize' %>box-sidebar<% end %>">
        <%= link_to( admin_optimize_index_path ) do %>
          <span class="<% if controller_name == 'optimize' %>label-sidebar<% end %>" style="font-size: 16px;font-weight: bold;">5º</span>
          <span class="sidebar-title">Otimizar produção</span>

          <span class="sidebar-title-tray" id="">
           
          </span>
        <% end %>
      </li>    
      <%end%>
    </ul>
    <!-- End: Sidebar Menu -->

  </div>
  <!-- End: Sidebar Left Content -->

</aside>
<!-- End: Sidebar Left -->